### ISSUE TITLE
CardSort Failing to Run.

### ISSUE THREAD

**Issue by ghost** [sugarlabs/cardsort#19]
Log activity
````user@debian:-/Activities/cardsorts sugar-activity3 Traceback (most recent call last):
File "/home/user/Activities/cardsort/CardSortActivity.py", line 106, in if self.metadata['grid'] == '2x2':
init
File "/usr/lib/python3.7/dist-packages/sugar3/datastore/datastore.py", line 105, in getitem return self._properties [key]
KeyError: 'grid'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/bin/sugar-activity3", line 5, in <module>
activityinstance.main()
File "/usr/lib/python3.7/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
instance = create_activity_instance(activity_constructor, activity_handle)
File "/usr/lib/python3.7/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance activity = constructor (handle)
File "/home/user/Activities/cardsort/CardSortActivity.py", line 116, in init
self.resize_grid(2,2)
File "/home/user/Activities/cardsort/CardSortActivity.py", line 123, in resize_grid self.game.grid.reset_game (self.game)
File "/home/user/Activities/cardsort/grid.py", line 185, in reset_game
self.test()
AttributeError: 'Grid' object has no attribute 'test'
````

exception when tried handling another exception.

**Comment by quozl** [comment]
Thanks.  Reproduced on Ubuntu 22.04 (Jammy).  `git bisect` shows the first bad commit is 909c9f50bb78af9dc2cab1a441bd364803a1fc7b by @marsian83.

**Comment by marsian83** [comment]
Interesting
I reckon this might be due to renaming the variable `test` to `test_borders` but it appears that in some places in the code `test` is still being called.
Simply renaming the function in places where it is called should fix it!
I might take a look later today.

**Comment by quozl** [comment]
Thanks!
